name: "CI: Linting Dockerfile"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      -
        name: Hadolint
        if: github.event_name != 'pull_request'
        uses: brpaz/hadolint-action@c27bd9edc1e95eed30474db8f295ff5807ebca14 # v1.5.0
        with: 
          dockerfile: Dockerfile
      -
        name: Hadolint for PR
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-hadolint@2436424949dbe43e4473f871405b2edbab8f0f6c # v1.48.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true